package com.refind.dao.impl;
import com.refind.dao.LocationDAO; import com.refind.database.DatabaseConnection; import com.refind.exception.DatabaseException; import com.refind.model.Location; import java.sql.*; import java.util.*;
public class JdbcLocationDAO implements LocationDAO {
 public Location save(Location x){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO locations(campus,building,room) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,x.getCampus());p.setString(2,x.getBuilding());p.setString(3,x.getRoom());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())x.setId(r.getLong(1));}return x;}catch(SQLException e){throw new DatabaseException("Failed to save location.",e);}}
 public Optional<Location> findById(Long id){return one("SELECT * FROM locations WHERE id=?",id);} private Optional<Location> one(String s,Object v){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setObject(1,v);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(JdbcMappers.location(r)):Optional.empty();}}catch(SQLException e){throw new DatabaseException("Failed to query location.",e);}}
 public List<Location> findAll(){List<Location>a=new ArrayList<>();try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM locations ORDER BY campus,building,room");ResultSet r=p.executeQuery()){while(r.next())a.add(JdbcMappers.location(r));return a;}catch(SQLException e){throw new DatabaseException("Failed to list locations.",e);}}
 public Location update(Location x){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE locations SET campus=?,building=?,room=? WHERE id=?")){p.setString(1,x.getCampus());p.setString(2,x.getBuilding());p.setString(3,x.getRoom());p.setLong(4,x.getId());if(p.executeUpdate()==0)throw new DatabaseException("Location not found: "+x.getId());return x;}catch(SQLException e){throw new DatabaseException("Failed to update location.",e);}}
 public boolean deleteById(Long id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM locations WHERE id=?")){p.setLong(1,id);return p.executeUpdate()>0;}catch(SQLException e){throw new DatabaseException("Failed to delete location.",e);}}
}
