package com.refind.dao.impl;
import com.refind.dao.NotificationDAO; import com.refind.database.DatabaseConnection; import com.refind.exception.DatabaseException; import com.refind.model.Notification; import java.sql.*; import java.util.*;
public class JdbcNotificationDAO implements NotificationDAO {
 public Notification save(Notification n){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO notifications(user_id,text,read_flag) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setLong(1,n.getUser().getId());p.setString(2,n.getText());p.setBoolean(3,n.isReadFlag());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())n.setId(r.getLong(1));}return findById(n.getId()).orElse(n);}catch(SQLException e){throw new DatabaseException("Failed to save notification.",e);}}
 public Optional<Notification> findById(Long id){return one("SELECT * FROM notifications WHERE id=?",id);} private Optional<Notification> one(String s,Object v){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setObject(1,v);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(JdbcMappers.notification(r)):Optional.empty();}}catch(SQLException e){throw new DatabaseException("Failed to query notification.",e);}}
 public List<Notification> findByUser(Long id){return list("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC",id);} public List<Notification> findUnreadByUser(Long id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM notifications WHERE user_id=? AND read_flag=FALSE ORDER BY created_at DESC")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){List<Notification>a=new ArrayList<>();while(r.next())a.add(JdbcMappers.notification(r));return a;}}catch(SQLException e){throw new DatabaseException("Failed to list unread notifications.",e);}}
 private List<Notification> list(String s,Object v){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setObject(1,v);try(ResultSet r=p.executeQuery()){List<Notification>a=new ArrayList<>();while(r.next())a.add(JdbcMappers.notification(r));return a;}}catch(SQLException e){throw new DatabaseException("Failed to list notifications.",e);}}
 public boolean markAsRead(Long id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE notifications SET read_flag=TRUE WHERE id=?")){p.setLong(1,id);return p.executeUpdate()>0;}catch(SQLException e){throw new DatabaseException("Failed to mark notification as read.",e);}}
 public boolean deleteById(Long id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM notifications WHERE id=?")){p.setLong(1,id);return p.executeUpdate()>0;}catch(SQLException e){throw new DatabaseException("Failed to delete notification.",e);}}
}
