package com.refind.dao.impl;
import com.refind.dao.ClaimDAO; import com.refind.database.DatabaseConnection; import com.refind.exception.DatabaseException; import com.refind.model.Claim; import com.refind.model.enums.ClaimStatus; import java.sql.*; import java.util.*;
public class JdbcClaimDAO implements ClaimDAO {
 public Claim save(Claim x){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO claims(user_id,item_id,message,status) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setLong(1,x.getClaimant().getId());p.setLong(2,x.getItem().getId());p.setString(3,x.getMessage());p.setString(4,(x.getStatus()==null?ClaimStatus.PENDING:x.getStatus()).name());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())x.setId(r.getLong(1));}return findById(x.getId()).orElse(x);}catch(SQLException e){throw new DatabaseException("Failed to save claim.",e);}}
 public Optional<Claim> findById(Long id){return one("SELECT c.*, i.type as item_type FROM claims c JOIN items i ON c.item_id = i.id WHERE c.id=?",id);} private Optional<Claim> one(String s,Object v){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setObject(1,v);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(JdbcMappers.claim(r)):Optional.empty();}}catch(SQLException e){throw new DatabaseException("Failed to query claim.",e);}}
 public List<Claim> findAll(){return list("SELECT c.*, i.type as item_type FROM claims c JOIN items i ON c.item_id = i.id ORDER BY c.submitted_at DESC",null);} public List<Claim> findByClaimant(Long id){return list("SELECT c.*, i.type as item_type FROM claims c JOIN items i ON c.item_id = i.id WHERE c.user_id=? ORDER BY c.submitted_at DESC",id);} public List<Claim> findByItem(Long id){return list("SELECT c.*, i.type as item_type FROM claims c JOIN items i ON c.item_id = i.id WHERE c.item_id=? ORDER BY c.submitted_at DESC",id);} public List<Claim> findByStatus(ClaimStatus s){return list("SELECT c.*, i.type as item_type FROM claims c JOIN items i ON c.item_id = i.id WHERE c.status=? ORDER BY c.submitted_at DESC",s.name());}
 private List<Claim> list(String s,Object v){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){if(v!=null)p.setObject(1,v);try(ResultSet r=p.executeQuery()){List<Claim>a=new ArrayList<>();while(r.next())a.add(JdbcMappers.claim(r));return a;}}catch(SQLException e){throw new DatabaseException("Failed to list claims.",e);}}
 public Claim update(Claim x){String sql="UPDATE claims SET user_id=?,item_id=?,message=?,status=?,decided_at=? WHERE id=?";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,x.getClaimant().getId());p.setLong(2,x.getItem().getId());p.setString(3,x.getMessage());p.setString(4,x.getStatus().name());if(x.getDecidedAt()==null)p.setNull(5,Types.TIMESTAMP);else p.setTimestamp(5,Timestamp.valueOf(x.getDecidedAt()));p.setLong(6,x.getId());if(p.executeUpdate()==0)throw new DatabaseException("Claim not found: "+x.getId());return findById(x.getId()).orElse(x);}catch(SQLException e){throw new DatabaseException("Failed to update claim.",e);}}
 public boolean deleteById(Long id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM claims WHERE id=?")){p.setLong(1,id);return p.executeUpdate()>0;}catch(SQLException e){throw new DatabaseException("Failed to delete claim.",e);}}
}
