package com.refind.dao.impl;
import com.refind.dao.CategoryDAO; import com.refind.database.DatabaseConnection; import com.refind.exception.DatabaseException; import com.refind.model.Category; import java.sql.*; import java.util.*;
public class JdbcCategoryDAO implements CategoryDAO {
 public Category save(Category x){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO categories(name) VALUES(?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,x.getName());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())x.setId(r.getLong(1));}return x;}catch(SQLException e){throw new DatabaseException("Failed to save category.",e);}}
 public Optional<Category> findById(Long id){return one("SELECT * FROM categories WHERE id=?",id);} private Optional<Category> one(String s,Object v){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setObject(1,v);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(JdbcMappers.category(r)):Optional.empty();}}catch(SQLException e){throw new DatabaseException("Failed to query category.",e);}}
 public List<Category> findAll(){List<Category> a=new ArrayList<>();try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM categories ORDER BY name");ResultSet r=p.executeQuery()){while(r.next())a.add(JdbcMappers.category(r));return a;}catch(SQLException e){throw new DatabaseException("Failed to list categories.",e);}}
 public Category update(Category x){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE categories SET name=? WHERE id=?")){p.setString(1,x.getName());p.setLong(2,x.getId());if(p.executeUpdate()==0)throw new DatabaseException("Category not found: "+x.getId());return x;}catch(SQLException e){throw new DatabaseException("Failed to update category.",e);}}
 public boolean deleteById(Long id){try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM categories WHERE id=?")){p.setLong(1,id);return p.executeUpdate()>0;}catch(SQLException e){throw new DatabaseException("Failed to delete category.",e);}}
}
